# alertmanager.yml

route:
  receiver: 'info'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 24h
  group_by: [cluster, alertname]
  # All alerts that do not match the following child routes
  # will remain at the root node and be dispatched to 'default-receiver'.
  routes:
  # All alerts with severity="error" are dispatched to the error pager.
  - receiver: 'error'
    group_wait: 10s
    matchers:
    - severity="error"
  # All alerts with the severity="warning" label match this sub-route.
  - receiver: 'warning'
    group_wait: 10s
    matchers:
    - severity="warning"

#channel for massege sender
receivers:
- name: "info"
  webhook_configs:
  - send_resolved: true
    url: "https://ip/hooks/Dy9FmqJxZWQaTw28p/2d89SG5uMZC9DEZDPRf4RHnk5C42NvdQBtkMZimjgbZRAafi"

- name: "error"
  webhook_configs:
  - send_resolved: true
    url: "http://telegram_alert"

